- .flake8
- src/funds/funds_meta.py
- src/impl/apis/funds_api.py
- src/tests/test_funds_api.py
> Fixed issue #15

- README.md
- src/database/models.py
- src/sync_handler/handler.py
- src/tests/data/backend-fund-rates-teardown.sql
- src/tests/data/backend-funds-teardown.sql
- src/tests/data/salkku-fund-securities-teardown.sql
- src/tests/data/salkku-raterah-teardown.sql
- src/tests/fixtures/backend_mysql.py
- src/tests/fixtures/salkku_mysql.py
- src/tests/fixtures/sync.py
- src/tests/test_funds_api.py
- src/tests/utils/database.py
> Feature 30 sync tests

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Feature 63 force recheck migration

- src/alembic/versions/0012_last_rate_updated.py
- src/commands/migrate.py
- src/commands/migration_tasks.py
- src/database/models.py
- src/tests/data/backend-last-rate.sql
> Hotfix 65 last rate not updated

- src/funds/funds_meta.py
> Removed fund change data cache

- src/funds/funds_meta.py
> Removed fund meta cache

- src/database/operations.py
- src/tests/test_portofolios_api.py
> Fixed issue #95

- src/business_logics/business_logics.py
- src/tests/test_portofolios_api.py
> Fixed issue #101

- src/holdings/holdings.py
- src/impl/apis/portfolios_api.py
- src/tests/test_holdings.py
> Hotfix 112 slow portfolio history

- src/alembic/versions/0017_company_updated.py
- src/commands/migration_tasks.py
- src/database/models.py
- src/tests/data/backend-company.sql
> Hotfixz 114 missing company id after migration

- src/business_logics/business_logics.py
- src/impl/apis/meetings_api.py
> missing 15:00 meeting time slot

- src/config/settings.py
> fix conversion date

- src/commands/migration_tasks.py
> Hotfix 131 removed portfolio transactions

- src/impl/apis/portfolios_api.py
- src/tests/test_portofolios_api.py
> Fixed issue #134

- src/alembic/versions/0018_fund_kiid_url_fi_nullable.py
- src/database/models.py
- src/impl/apis/funds_api.py
> Feature 137 optional kiid

- src/funds/funds_meta.py
- src/impl/apis/funds_api.py
> Changed fund translator to use secid as fallback for change data lookup

- src/impl/apis/portfolios_api.py
> Fix for issue #144

- src/database/operations.py
- src/impl/apis/portfolios_api.py
- src/tests/test_portofolios_api.py
- src/utils/currency_utils.py
- src/utils/portfolio_utils.py
> Fix for issue #147

- src/impl/apis/securities_api.py
- src/tests/test_securities_api.py
> Fixed issue #150

- src/impl/apis/meetings_api.py
- src/requirements.in
- src/requirements.txt
> Fixed issue #156

- src/impl/apis/meetings_api.py
> Fixed issue #162

- src/commands/migration_tasks.py
> Fixed issue #166

- src/alembic/versions/0021_create_synchronization_failure_table.py
- src/commands/migrate.py
- src/commands/migration_exception.py
- src/commands/migration_exceptions.py
- src/commands/migration_tasks.py
- src/database/models.py
- src/impl/apis/meetings_api.py
- src/mail/mailer.py
> Feature 171 automatic force sync

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Added support for skipping migration tasks

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Initial draft of migration verifications

- src/database/operations.py
- src/impl/apis/companies_api.py
- src/impl/apis/portfolios_api.py
- src/spec/apis/companies_api.py
- src/spec/apis/portfolios_api.py
- src/tests/test_companies_api.py
- src/tests/test_portofolios_api.py
> Feature 179 list companies

- src/commands/migrate.py
- src/commands/migration_tasks.py
- src/database/operations.py
- src/impl/apis/funds_api.py
- src/tests/test_funds_api.py
> Feature 181 fund price date

- src/alembic/versions/0023_portfolio_log_add_c_company.py
- src/commands/log_ccom.py
- src/commands/migration_tasks.py
- src/database/models.py
- src/impl/apis/portfolios_api.py
> Hotfix 183 portfolio history to port

- src/impl/apis/portfolios_api.py
- src/spec/apis/portfolios_api.py
- src/tests/test_portofolios_api.py
> Feature 190 versioned portfolio list

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Hotfix 194 reference constraint error while removing company

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Feature 199 security based migrations

- src/commands/migration_tasks.py
> Fixes issue #208

- src/commands/migration_tasks.py
> Fixes issue #208 nulls

- src/commands/migrate.py
- src/commands/migration_tasks.py
> Hotfix 208 optimize count
